### ISSUE TITLE
montgomery representation

### ISSUE THREAD

**Issue by TalDerei** [ingonyama-zk/icicle#16]
https://github.com/ingonyama-zk/icicle/blob/00231723b9fe0e2d7cbfc3202109cd6399b4c523/icicle/curves/bls12_381.cuh#LL27C41-L27C44

This is usually represented as the montgomery form of 1 if you want to convert to between affine/jacobian/projective forms: https://github.com/ingonyama-zk/icicle/blob/main/icicle/primitives/projective.cuh#L23

**Comment by DmytroTym** [comment]
This has to do with the answer to the [previous issue](https://github.com/ingonyama-zk/icicle/issues/11#issuecomment-1474368626) you opened, namely that we don't use Montgomery multiplication. If we succeed in having competitive no-Montgomery multiplier, the config file can stay the way it is. If we don't and we have to move to Montgomery, then you're right, `one` needs to be one in Montgomery form, and not just plain one.

**Comment by DmytroTym** [comment]
I feel like this can be closed due to https://github.com/ingonyama-zk/icicle/pull/289
We are on par with the state-of-the art Montgomery multiplier so it feels like there's no urgency to move to it. Can be reopened if people improve Montgomery multiplication or we just decide to support Montgomery as well.
