### ISSUE TITLE
[DOCS]: Document root of unity and its implications 

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#182]
## Description

Please provide a clear and concise description of the feature you would like included.

## Motivation

Please provide a clear and concise description of the motivation for adding this feature.

**Comment by DmytroTym** [comment]
Since this issue was opened, the way root of unity is used changed a bit, nowadays it's passed into the `init_domain` function by the user, and not implicitly chosen by us. See [C++ side function](https://github.com/ingonyama-zk/icicle/blob/main/icicle/appUtils/ntt/ntt.cuh#L37) and [her Rust equivalent](https://github.com/ingonyama-zk/icicle/blob/main/wrappers/rust/icicle-core/src/ntt/mod.rs#L118). I feel like their documentation is ok so closing this
