### ISSUE TITLE
Compilation time

### ISSUE THREAD

**Issue by TalDerei** [ingonyama-zk/icicle#63]
Is there any way to speed up the slow Rust compilation time after making a change to the C++ functions? How is the dev team going about testing C++ functions via Rust FFI otherwise? Thanks!

**Comment by omershlo** [comment]
cc @vhnatyk

**Comment by vhnatyk** [comment]
Hi @TalDerei ) In case you do like really a lot of frequent changes, I suggest you to create simple wrapping .cu file and build/run it with something like for example `nvcc run_me.cu -o run_me; ./run_me`. 

But since we disabled debug builds by [default](https://github.com/ingonyama-zk/icicle/blob/9765a740edf19ed9d130880626883f8eb9d602f4/build.rs#L21) - it doesn't seem to be taking too much time, around 15-30sec on average 8core desktop. 

Occasionally if more .cu files were changed it can take a minute. Of course you need to run Rust in release mode as well by adding `--release` to cargo commands, like `cargo run --release'. Otherwise debug host flag is added by cargo and build indeed may take minute or two.

Hope it helps:)

**Comment by vhnatyk** [comment]
@TalDerei  I guess we can close this one. @TalDerei  @LeonHibnik  wdyt? we can reopen ofc

**Comment by vhnatyk** [comment]
Reopening since we added more curves and compilation times are huge now, good news there is a fix for subsequent compilation
