### ISSUE TITLE
[BUG]: Detect GPU arch at config time or plz mention in README

### ISSUE THREAD

**Issue by Geof23** [ingonyama-zk/icicle#67]
## Description

Was building and running the CUDA test suite; every test but one was failing with 500 (_named symbol not found_).  It went over my head for a minute

### Reproduce

Build & run tests with sub *80* hardware

## Expected Behavior

For the tests to run and complete calls to CUDA kernels

## Environment

WSL2, gcc 11.3,  CUDA 12.1, CMake 3.22.1

OS + Version:

Ubuntu 22.04.1 LTS

Cargo Version:

Not installed

GPU type:

GTX-2060RTX

## Additional context

Well, at least with *CMake 3.24*, this is available:

[`native` architecture](https://cmake.org/cmake/help/latest/release/3.24.html?highlight=cuda_architectures)

**Comment by omershlo** [comment]
thanks @Geof23 -  we are looking into it and will update soon

**Comment by robik75** [comment]
Hi @Geof23,
as you correctly pointed out, the tests fail on older architectures than 8.0.
This is because the default architecture in is set to 8.0 here: https://github.com/ingonyama-zk/icicle/blob/main/icicle/CMakeLists.txt#L11-L14 .
You can still build for a different architecture by setting `CMAKE_CUDA_ARCHITECTURES` to your desired architecture(s) when running the build script by modifying the `cmake -S . -B build` command and adding the `CMAKE_CUDA_ARCHITECTURES` definition, for example like this: `cmake -S . -B build -DCMAKE_CUDA_ARCHITECTURES=70`.
I suggest that the library maintainers mention this option in the README.
Please let me know if this solves your problem.

**Comment by Geof23** [comment]
Thank you for your responses

**Comment by omershlo** [comment]
@vhnatyk/ @LeonHibnik  please update Readme
